[pytest]
testpaths = tests
filterwarnings =
    ignore:The property ``qiskit.circuit.instruction.Instruction.condition`` is deprecated:DeprecationWarning
    ignore:Using `httpx` with `starlette.testclient` is deprecated
